import Link from 'next/link'
import '@/app/globals.css'

export const metadata = {
  title: 'My awesome site',
  description: 'Generated by Next + Sanity!',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-3xl py-10 mx-auto'>
        <header>
          <Link href={"/"} className='text-lg font-bold text-transparent bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text'>Shanok</Link>
        </header>
        <main className='py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
